import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import {ToastContainer} from "react-toastify"
import { Inter, Geist } from 'next/font/google'
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html
      lang="pt-BR" data-scroll-behavior="smooth"
      className={cn("h-full", "antialiased", "max-w-screen-3xl", "mx-auto", inter.className, "font-sans", geist.variable, playfair.className)}
    >
      <body className="w-full min-h-full flex flex-col">
        <Header/>
        {children}
        <ToastContainer/>
        <Footer/>
        </body>
    </html>
  );
}


